#!/usr/bin/env bash
# This installs all the npm dependencies listed in the "Vue Tools" section.

npm install -D eslint-config-prettier
npm install -D eslint-plugin-html
npm install -D eslint-plugin-import
npm install -D eslint-plugin-prettier
npm install -D @vue/eslint-config-prettier
npm install -D prettier
npm install -D eslint-config-prettier
npm install -D eslint-plugin-html
npm install -D eslint-plugin-import
npm install -D eslint-plugin-prettier
npm install -D @vue/eslint-config-prettier
npm install -D prettier
